OBJ= aacur.o analy.o aver.o axeint.o bacint.o backbo.o bonder.o   \
calc.o cubspl.o deriv.o diff.o eigen.o grads.o gradt.o grgrap.o   \
groove.o input.o locate.o locpar.o lsfit.o mc11a.o minfor.o   \
move.o nml.o outaxe.o params.o pdbout.o plate.o setd.o setend.o   \
setup.o title.o torp.o up.o 
FLAG=
Cur5_s:  $(OBJ)
	gfortran $(FLAG) $(OBJ) -o Cur5
aacur.o:  aacur.f
	gfortran $(FLAG) -static -c  aacur.f
analy.o:  analy.f
	gfortran $(FLAG) -static -c  analy.f
aver.o:  aver.f
	gfortran $(FLAG) -static -c  aver.f
axeint.o:  axeint.f
	gfortran $(FLAG) -static -c  axeint.f
bacint.o:  bacint.f
	gfortran $(FLAG) -static -c  bacint.f
backbo.o:  backbo.f
	gfortran $(FLAG) -static -c  backbo.f
bonder.o:  bonder.f
	gfortran $(FLAG) -static -c  bonder.f
calc.o:  calc.f
	gfortran $(FLAG) -static -c  calc.f
cubspl.o:  cubspl.f
	gfortran $(FLAG) -static -c  cubspl.f
deriv.o:  deriv.f
	gfortran $(FLAG) -static -c  deriv.f
diff.o:  diff.f
	gfortran $(FLAG) -static -c  diff.f
eigen.o:  eigen.f
	gfortran $(FLAG) -static -c  eigen.f
grads.o:  grads.f
	gfortran $(FLAG) -static -c  grads.f
gradt.o:  gradt.f
	gfortran $(FLAG) -static -c  gradt.f
grgrap.o:  grgrap.f
	gfortran $(FLAG) -static -c  grgrap.f
groove.o:  groove.f
	gfortran $(FLAG) -static -c  groove.f
input.o:  input.f
	gfortran $(FLAG) -static -c  input.f
locate.o:  locate.f
	gfortran $(FLAG) -static -c  locate.f
locpar.o:  locpar.f
	gfortran $(FLAG) -static -c  locpar.f
lsfit.o:  lsfit.f
	gfortran $(FLAG) -static -c  lsfit.f
mc11a.o:  mc11a.f
	gfortran $(FLAG) -static -c  mc11a.f
minfor.o:  minfor.f
	gfortran $(FLAG) -static -c  minfor.f
move.o:  move.f
	gfortran $(FLAG) -static -c  move.f
nml.o:  nml.f
	gfortran $(FLAG) -static -c  nml.f
outaxe.o:  outaxe.f
	gfortran $(FLAG) -static -c  outaxe.f
params.o:  params.f
	gfortran $(FLAG) -static -c  params.f
pdbout.o:  pdbout.f
	gfortran $(FLAG) -static -c  pdbout.f
plate.o:  plate.f
	gfortran $(FLAG) -static -c  plate.f
setd.o:  setd.f
	gfortran $(FLAG) -static -c  setd.f
setend.o:  setend.f
	gfortran $(FLAG) -static -c  setend.f
setup.o:  setup.f
	gfortran $(FLAG) -static -c  setup.f
title.o:  title.f
	gfortran $(FLAG) -static -c  title.f
torp.o:  torp.f
	gfortran $(FLAG) -static -c  torp.f
up.o:  up.f
	gfortran $(FLAG) -static -c  up.f
