freeglut (/home/xiangjun/Tools/pymol/pymol.exe): Unable to create direct context rendering for window 'PyMOL Viewer'
This may hurt performance.

 PyMOL(TM) Incentive Product - Copyright (C) 2006 DeLano Scientific LLC.
 
 A current PyMOL Maintenance and/or Support Subscription may be required
 for legal use of this Build beyond a finite honor-system evaluation period.
 Please visit http://www.pymol.org/funding.html for more information.
 
 This PyMOL Executable Build incorporates Open-Source PyMOL 0.99rc6.
 OpenGL graphics engine:
  GL_VENDOR: Mesa project: www.mesa3d.org
  GL_RENDERER: Mesa GLX Indirect
  GL_VERSION: 1.2 (1.5 Mesa 6.4.1)
PyMOL>delete all
PyMOL>load 1kx5_s1.r3d
 Executive: object "1kx5_s1" created.
PyMOL>set orthoscopic, 1
 Setting: orthoscopic set to on.
PyMOL>set antialias, 1
 Setting: antialias set to 1.
PyMOL>set ambient, 0.5
 Setting: ambient set to 0.50000.
PyMOL>set direct, 0.8
 Setting: direct set to 0.80000.
PyMOL>set gamma, 2
 Setting: gamma set to 2.00000.
PyMOL>set spec_power, 100
 Setting: spec_power set to 100.00000.
PyMOL>set hash_max, 175
 Setting: hash_max set to 175.
PyMOL>zoom *, 1
PyMOL>bg_color white
PyMOL>ray 2100
 Ray: render time: 7.87 sec. = 457.6 frames/hour (7.87 sec. accum.).
PyMOL>png x3dna_r3d_pymol.png
 ScenePNG: wrote 2100x1575 pixel image to file "x3dna_r3d_pymol.png".
PyMOL>quit
 PyMOL: normal program termination.
